apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-dns-viewer
subjects:
  - kind: ServiceAccount
    name: dns-sync
    namespace: {{ .Release.Namespace }}
