apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: dns-sync

      shareProcessNamespace: true
      terminationGracePeriodSeconds: 5
      containers:
        - name: app
          image: {{ .Values.image.repository }}/dns-sync:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          workingDir: /var/run/dns
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: http-metrics
              protocol: TCP
              containerPort: 9001
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: http-metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1

          volumeMounts:
            - name: cfg
              mountPath: /var/run/dns

          {{- if .Values.extraVolumeMounts }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: cfg
          configMap:
            name: {{ .Release.Name }}
            optional: true

      {{- if .Values.extraVolumes }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
