apiVersion: v2
name: dns-sync
description: DNS sync based on ExternalDNS
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - kubernetes
  - externaldns
  - external-dns
  - dns
  - service
  - ingresss
